### ISSUE TITLE
Wingpanel error with DBus

### ISSUE THREAD

**Issue by kepicorp** [elementary/wingpanel-indicator-session#115]
## Prerequisites
- [ X] I have searched open and closed issues for duplicates.

## Describe the bug

When I try to access the wingpanel I got a freeze (debug log of dbus-montior bellow).

P.S: The doc is deprecated https://elementary.io/docs/code/os-dev#wingpanel as it seems that wingpanel is not started by cerbere anymore.

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Access the session menu in wingpanel
 Freeze occur

### Expected behavior

It should just open the menu

### Logs

Logs from dbus-monitor:

method call time=1586442201.039905 sender=:1.124 -> destination=:1.53 serial=82 path=/org/freedesktop/ScreenSaver; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.ScreenSaver"
error time=1586442201.040482 sender=:1.53 -> destination=:1.124 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=82

and

method call time=1586442201.044591 sender=:1.124 -> destination=org.freedesktop.DBus serial=86 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.freedesktop.DisplayManager"
   uint32 0
error time=1586442201.044876 sender=org.freedesktop.DBus -> destination=:1.124 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=86

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ X] I'm using the latest released stable version

## Additional context

I already recompiled a libsession ones where I remove all call to DBus to make it work but this is being broken everytime there is an update to wingpanel.

It must be a fundamental flaw in my dbus session.

**Comment by davidmhewitt** [comment]
You are using the normal elementary greeter (lightdm) right? You haven't replaced it or modified it in some way?

**Comment by kepicorp** [comment]
Yes standard greeter
/etc/lightdm/io.elementary.greeter.conf
[greeter]
#activate-numlock=true
#default-wallpaper=/usr/share/backgrounds/elementaryos-default
#high-contrast=false
#onscreen-keyboard=false
#screensaver-timeout=60

**Comment by davidmhewitt** [comment]
And I remember asking you this before, but can you post the full log from wingpanel in the terminal? You'll need to kill it twice to stop the auto-restart by running `killall wingpanel` twice, then you can start it with:

`G_MESSAGES_DEBUG=all wingpanel`

**Comment by kepicorp** [comment]
What is doing the autorestart as it's not cerbere anymore ? (and yes we already had a conv about this before)

**Comment by davidmhewitt** [comment]
`gnome-session` is doing the auto-restart now, we've always used it to start the session, but now we're using it to restart things too.

I'd still like to see the logs now that we've retired cerbere and have merged in a few other bits of debugging code.

**Comment by kepicorp** [comment]
I just pinpointed the problem to dbus error, as debug log in wingpanel don't give much more infos ...

```log
(wingpanel:8234): DEBUG: 10:51:06.981: Volume-control.vala:653: Setting volume to 0.280029 for profile -1 because 0

(wingpanel:8234): Gtk-CRITICAL **: 10:51:06.982: gtk_widget_set_no_show_all: assertion 'GTK_IS_WIDGET (widget)' failed

(wingpanel:8234): Gtk-CRITICAL **: 10:51:06.982: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.029: ActUserManager: calling 'ListCachedUsers'
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.030: ActUserManager: Listing cached users, so not setting loaded property
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.036: ActUserManager: ListCachedUsers finished, will set loaded property after list is fully loaded
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.036: ActUserManager: tracking new user with object path /org/freedesktop/Accounts/User1000
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.045: ActUserManager: unrefing manager owned by finished ListCachedUsers call
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.051: ActUserManager: user pierre is now loaded
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.051: ActUserManager: user pierre was not yet known, adding it
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.051: ActUserManager: tracking user 'pierre'
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.051: ActUserManager: not yet loaded, so not emitting user-added signal
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.051: ActUserManager: no pending users, trying to set loaded property
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.051: ActUserManager: Seat still actively loading, so not setting loaded property
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.079: ActUserManager: Seat still actively loading, so not setting loaded property
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.079: ActUserManager: Seat still actively loading, so not setting loaded property
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.080: ActUserManager: Found x11 display of session 'c2': :0
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.080: ActUser: adding session c2
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.080: ActUserManager: added session for user pierre
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.080: ActUserManager: Seat loaded, so now setting loaded property
(wingpanel:8234): AccountsService-DEBUG: 10:52:28.094: ActUserManager: already loaded, so not setting loaded property
** (wingpanel:8234): DEBUG: 10:52:31.990: Device.vala:165: Connection to UPower device established
** (wingpanel:8234): DEBUG: 10:52:31.992: Indicator.vala:117: Icon changed to "battery-full-charging-symbolic"
** (wingpanel:8234): DEBUG: 10:52:31.994: Device.vala:165: Connection to UPower device established
** (wingpanel:8234): DEBUG: 10:52:32.062: DeviceManager.vala:126: Device "/org/freedesktop/UPower/devices/line_power_AC" registered
** (wingpanel:8234): DEBUG: 10:52:32.066: Device.vala:165: Connection to UPower device established
** (wingpanel:8234): DEBUG: 10:52:32.069: DeviceManager.vala:126: Device "/org/freedesktop/UPower/devices/battery_BAT0" registered
** (wingpanel:8234): DEBUG: 10:52:32.094: Monitor.vala:42: Initialising process monitor.
** (wingpanel:8234): DEBUG: 10:52:32.132: Indicator.vala:117: Icon changed to "battery-full-charging-symbolic"

** (wingpanel:8234): CRITICAL **: 10:52:32.325: session_widgets_userbox_update_state: assertion 'self != NULL' failed

```

**Comment by davidmhewitt** [comment]
So I guess in this case, you clicked the indicator around 10:51:06 and then it took until 10:52:28 to do anything?

**Comment by kepicorp** [comment]
correct !

**Comment by kepicorp** [comment]
Should I just reinstall lightdm and gala ?

**Comment by kepicorp** [comment]
I will do a full reinstall and debug my dconf on my side thanks !

**Comment by davidmhewitt** [comment]
I suspect that https://github.com/elementary/wingpanel-indicator-session/pull/116 will reduce the amount of time it takes to open the indicator, but I have absolutely no idea why connections to this DBus interface take so long on your computer (and only your computer).

**Comment by kepicorp** [comment]
building the latest master and will check it out
