### ISSUE TITLE
Session indicator menu displays keyboard shortcuts with inconsistent versions

### ISSUE THREAD

**Issue by stayinside4ever** [elementary/wingpanel-indicator-session#130]
See screenshot below. I only have a "Windows" keyboard, no idea why it's showing me shortcuts with the Command button as well as the "Windows" ones.

![Screenshot from 2020-07-07 11 33 33](https://user-images.githubusercontent.com/12560935/86768846-13c2d200-c046-11ea-80eb-23e7f22f5bf7.png)

This is on elementary OS 5.1.5 Hera

Edit: realised that it locks the screen with `Windows key + L`. Design flaw then, possibly, since my immediate thought there is "I don't have a Mac keyboard" instead of "oh, so it's the Windows key"?

**Comment by lainsce** [comment]
While it has been popularised by mac keyboards, the loop square symbol (⌘) is actually a neutral Unicode way to show the Super key (or in Windows's terms, Windows key).

Check out [this wikipedia article](https://en.wikipedia.org/wiki/Looped_square) that details where it came from.

**Comment by danrabbit** [comment]
This is intentional. We always use the looped square symbol to represent the Windows/Command/Super key

Cassidy wrote a blog post about this a while ago for more background info: https://blog.elementary.io/why-the-looped-square-symbol/

**Comment by stayinside4ever** [comment]
After reading the article, I see your reasoning, yet I still feel like this could create a lot of confusion for the less tech-savvy users who wouldn't know the history and all? For example, if I installed elementary on my grandmother's computer, she would have zero idea what the looped square is (especially never having used a Mac), and not have sufficient English knowledge to Google it (and, even if she did, the first two results for "looped square key" mention only Apple keyboards, at least in the summaries). In her eyes at that point, there's a lot of shortcuts with a key that does not even exist on her keyboard.

Besides, surely, if one needs to read an article to understand what key to use for a shortcut that's already displayed on the screen, that's not the fault of the user...?

**Comment by lainsce** [comment]
Yes, but to use the Windows flag, means we're infringing on its copyright, and might have to pay some fee to Microsoft to be able to use it.
