### ISSUE TITLE
Shutdown action not working

### ISSUE THREAD

**Issue by paledega** [elementary/wingpanel-indicator-session#136]
shutdown not working:

```
** (wingpanel:21798): WARNING **: 14:27:55.467: EndSessionDialog.vala:178: Unable to shutdown: GDBus.Error:org.freedesktop.DBus.Error.InteractiveAuthorizationRequired: Interactive authentication required.

```
How can I fix this

**Comment by paledega** [comment]
I can shutwdown my machine with `shutdown -h now` command. but wingpanel applet not working

**Comment by paledega** [comment]
I am non-elementary distro user (sulinos)
shutdown working with gnome and other desktops

**Comment by tintou** [comment]
You need the polkit agent to be running, please rise this issue to your distro maintainer as we aren't responsible for your configuration.

**Comment by paledega** [comment]
I run consolekit manually. 
now working.

I ran `console-kit-daemon --no-daemon` command as root.
