### ISSUE TITLE
Popover widget does not show new user

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/wingpanel-indicator-session#146]
## What Happened

Popover widget does not show new user when a new user is added.

![screen-capture](https://user-images.githubusercontent.com/31680656/102714487-cabbbd00-4309-11eb-8e11-aec55a591d3d.gif)

Segmentation fault at the end of the gif seems to be a separate issue.

## Expected Behavior

Newly added user should be shown in popover widget.

## Steps to Reproduce

1. Add new user from switchboard.
2. Click session indicator.

## Platform Information

eOS6 daily. Master session indicator.

**Comment by pongloongyeat** [comment]
Actually, this might be localised to my session since I messed with `AccountsManager` but please leave this open, I'm planning on performing a fresh reinstall and I'll update it and check again.

**Comment by pongloongyeat** [comment]
Did a fresh reinstall today and problem persists.

**Comment by andrewdbate** [comment]
I can confirm that I have the same problem on a fresh install of elementary OS 6.1. Newly created users do not show in the session indicator.
