### ISSUE TITLE
Hide users from the menu

### ISSUE THREAD

**Issue by robertsanseries** [elementary/wingpanel-indicator-session#15]
There is no way to hide when there are many users

![users](https://cloud.githubusercontent.com/assets/11967501/25768425/12b8ca5c-31da-11e7-86ad-4ba1e41f3076.png)

**Comment by danrabbit** [comment]
Just out of curiosity what is your display resolution? There should be a scroll box which should keep the indicator from covering the panel like that

**Comment by robertsanseries** [comment]
Dell Lcd Monitor 17 Inches E178fpc Maximum Resolution: 1280 x 1024
