### ISSUE TITLE
Do not show the Suspend option when it is not supported

### ISSUE THREAD

**Issue by andrewdbate** [elementary/wingpanel-indicator-session#166]
### Problem

The session menu always shows the Suspend option even when it is not supported by the system.

If it is not supported by the system, then clicking the Suspend option does nothing. This is somewhat confusing at first.

Here is a video (26 seconds) to show what happens:

https://user-images.githubusercontent.com/2998569/143161791-ec69b167-0b7c-45ac-a1ae-e1fa9c3b174d.mp4

Note that there has been a previous request to add an option to remove Suspend from the session menu in the past: https://github.com/elementary/wingpanel-indicator-session/issues/73.

However please do note the different motivation here: I am suggesting to not show the Suspend option only if it does not work on a system (although I personally would be fine with a configuration setting not exposed in the UI if determining what systemd reports is too complicated to implement).

(If you are wondering why the system does not support suspend, some hardware does not support ACPI S3 because it only supports S4, but S4 is unreliable on Linux as has been discussed elsewhere. It can also happen because of network drivers or because of systemd configuration. But whatever the reason I believe that what systemd reports should be taken as-is: either the system supports it or it doesn't.)

### Proposal

If the system does not support suspend, i.e., the output of `systemctl suspend` reports:
```
Failed to suspend system via logind: Sleep verb "suspend" not supported
```
then the Suspend option should not be shown in the menu.

**Comment by aitor-gomila** [comment]
I want to work on this:
> Systemd-logind via the org.freedesktop.login1.Manager interface of the system bus does provide a "CanSuspend" method to know if the system is able to suspend or not though.
