### ISSUE TITLE
Apparent unclean shutdowns or restarts

### ISSUE THREAD

**Issue by vjr** [elementary/wingpanel-indicator-session#173]
### What Happened?

Shutting down or restarting via the `EndSessionDialog` is apparently unclean, meaning at least Google Chrome browser reports it was not closed cleanly and prompts to restore tabs (if the "continue where you left off" option is disabled in the "On Startup" section of its settings) upon relaunching the browser after a restart.

See [this comment](https://github.com/elementary/triage/issues/155#issuecomment-1345245747) in likely related issue https://github.com/elementary/triage/issues/155 which could potentially have the same root cause and fix.

### Steps to Reproduce

1. Open a few tabs in Google Chrome browser.
2. Ensure "continue where you left off" option is disabled in the "On Startup" section of its settings.
3. Restart the computer from the session indicator.
4. Relaunch browser and observe the message indicating it was not cleanly closed and offers to restore tabs.

### Expected Behavior

Chrome browser should open cleanly without prompting to restore tabs due to unclean shutdown.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
NA
```

### Hardware Info

NA

**Comment by vjr** [comment]
Related issue https://github.com/elementary/session-settings/issues/17

**Comment by danirabbit** [comment]
Seems like maybe a duplicate of #27 ?

**Comment by vjr** [comment]
Yes looks like it's a dupe. Closing this one now that it's at least linked to that so the notes are visible.
