### ISSUE TITLE
Bring back the suspend option

### ISSUE THREAD

**Issue by tintou** [elementary/wingpanel-indicator-session#178]
The suspend button is now conditionally shown whether the `lock-on-suspend` property is set to true or false.

This property specifies whether the session will be locked after coming back from suspend or not, so this is unrelated here.

Systemd-logind via the `org.freedesktop.login1.Manager` interface of the system bus does provide a "CanSuspend" method to know if the system is able to suspend or not though.

**Comment by aitor-gomila** [comment]
I want to work on this
