### ISSUE TITLE
Tray icons blurry in high DPI screens

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/wingpanel-indicator-session#179]
When setting the monitor to use a **higher DPI** than 1x, some icons on the tray are blurry. This could be expected for third party apps, but never for system apps.

(Bluetooth tray, notifications tray, and night light tray)

![Screenshot from 2023-04-17 19 29 51@2x](https://user-images.githubusercontent.com/46191980/232564246-b7bc3c07-5b32-4688-8d46-0d0ecc2bae9f.png)

This is an important issue for people with higher DPI monitors.

**Comment by lenemter** [comment]
Thanks for reporting! These icons have recently been updated and AFAIK they support HiDPI now.
