### ISSUE TITLE
'Lock' menu option doesn't work

### ISSUE THREAD

**Issue by btd1337** [elementary/wingpanel-indicator-session#53]
Hitting the 'lock' item in the session indicator doesn't do anything. Manually locking with dm-tool lock works.

> Reopened because this https://github.com/elementary/greeter/issues/92 was closed, but problem not was solved.

**Comment by osiyuk** [comment]
I confirm this, Lock item do not do anything, dm-tool works.
```
$ light-locker-command --lock
** Message: 05:51:43.183: Received error message from the locker: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
```

**Comment by jeremypw** [comment]
Can you confirm whether you are still experiencing this?  The lock option is working for me using the master version.

**Comment by worldofpeace** [comment]
Something has to provide `org.freedesktop.ScreenSaver`. In Pantheon this would be `light-locker` running.

@btd1337 Do you have `light-locker` installed? (it's started through the xdg autostart)

**Comment by btd1337** [comment]
@worldofpeace After 14 months of the bug I gave up the Pantheon.

**Comment by cassidyjames** [comment]
Closing as we can't reproduce in stable or master.
