### ISSUE TITLE
Extra click required after canceling session dialog

### ISSUE THREAD

**Issue by vjr** [elementary/wingpanel-indicator-session#61]
If you bring up the logout/shutdown dialog and click cancel, then to open the session indicator main dialog (user list) again you need to click twice. The first click after canceling does not seem to do anything.

Steps to repro:

1. click the indicator session icon and select shutdown
2. click cancel on the shutdown dialog
3. click indicator session icon, nothing happens
4. click indicator session icon again a second time and it works as expected

**Comment by vjr** [comment]
This happens both in the greeter and desktop.

**Comment by jeremypw** [comment]
A similar issue is experienced after returning from the lock option.

**Comment by vjr** [comment]
Thanks for testing - I also experience this for the suspend option - so fixed for both lock and suspend in the PR.
