### ISSUE TITLE
CTRL+ALT+DEL does not show logout/shutdown dialog

### ISSUE THREAD

**Issue by vjr** [elementary/wingpanel-indicator-session#62]
I get the following error in /var/log/syslog:

> Sep 12 13:13:06 zenbird gnome-session[1141]: gnome-session-binary[1141]: WARNING: Unable to open shell end session dialog: GDBus.Error:org.freedesktop.DBus.Error.Failed: io.elementary.wingpanel.session.EndSessionDialog DBus interface is not registered.
> Sep 12 13:13:06 zenbird gnome-session-binary[1141]: WARNING: Unable to open shell end session dialog: GDBus.Error:org.freedesktop.DBus.Error.Failed: io.elementary.wingpanel.session.EndSessionDialog DBus interface is not registered.

**Comment by ryonakano** [comment]
Duplication of #57
