### ISSUE TITLE
Option to remove "Suspend" button from session menu

### ISSUE THREAD

**Issue by DanyGee** [elementary/wingpanel-indicator-session#73]
An additional option in `System Settings` -> `Power` to disable the `Suspend` button in session menu might be nice for users not using any hibernation or suspend.
If a user sets all suspend/hibernation options to off, he most probably does not need that option in the session menu. Besides, it can also be accidently clicked when user tries to reach the `Shut Down` button.

**Comment by arshubham** [comment]
@DanyGee I am against adding an unnecessary option here. One use case for suspend I use is on desktops. I don't want to automatically suspend so I disable it. However I frequently use suspend in stead of full shutdown. Moreover suspend is non destructive action.

**Comment by cassidyjames** [comment]
I'm inclined to close this as a design conflict since we typically avoid adding configuration options like this.
