### ISSUE TITLE
phpstorm issue after package upgrade

### ISSUE THREAD

**Issue by m1ndgr3p** [elementary/wingpanel-indicator-session#86]
Greetings. after upgrade package wingpanel-indicator-session:amd64 from version `2.2.4+r313+pkg18~ubuntu5.0.1` to `2.2.5+r316+pkg19~ubuntu5.0.1` I faced an issue. phpstorm starts but window is transparent and nothing I can do just close it. package removal solve an issue. Please, would you be so kind, check this point in future releases.

**Comment by peteruithoven** [comment]
Does this transparency issue happen after you've interacted with the indicator? Could you share a screenshot (always share screenshots) of the issue?

I don't see how an indicator could have such an effect on your application... 
Especially seeing the changes: https://github.com/elementary/wingpanel-indicator-session/compare/2.2.4...2.2.5
There for example have been no changes to dependencies.

**Comment by m1ndgr3p** [comment]
sorry, it's my fail.
attached.
nope, no interaction with indicator.
![Screenshot from 2019-07-21 04-50-52](https://user-images.githubusercontent.com/9917481/61589077-45ac0180-ab73-11e9-931c-ba849f7da4fc.png)

**Comment by m1ndgr3p** [comment]
it's really strange. I tried to make screenshot of active window and application appears, but screenshot was not created...
